"""Type stubs for `vecnorm._native`."""

from __future__ import annotations

import numpy as np
from numpy.typing import NDArray

__version__: str

class VecnormError(Exception): ...

def l2_normalize(matrix: NDArray[np.float32]) -> None: ...
def l2_normalize_copy(matrix: NDArray[np.float32]) -> NDArray[np.float32]: ...
def cosine_similarity(a: NDArray[np.float32], b: NDArray[np.float32]) -> float: ...
def cosine_distances(a: NDArray[np.float32], b: NDArray[np.float32]) -> NDArray[np.float32]: ...
def top_k(scores: NDArray[np.float32], k: int) -> list[tuple[int, float]]: ...
def batch_top_k(
    scores: NDArray[np.float32], k: int, parallel: bool = False
) -> list[list[tuple[int, float]]]: ...
